"""Pydantic data models and schemas for the LLM Gateway."""

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, model_validator


class Role(str, Enum):
    """Message roles for chat interactions."""

    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class ChatMessage(BaseModel):
    """Individual message in a conversation sequence."""

    role: Role = Field(..., description="Role of the message sender")
    content: str = Field(..., description="Text content of the message", min_length=1)


class TokenUsage(BaseModel):
    """Token consumption accounting."""

    prompt_tokens: int = Field(default=0, ge=0, description="Tokens in input prompt")
    completion_tokens: int = Field(default=0, ge=0, description="Tokens generated by model")
    total_tokens: int = Field(default=0, ge=0, description="Total tokens consumed")

    @model_validator(mode="after")
    def compute_total(self) -> "TokenUsage":
        """Ensure total_tokens equals sum of prompt and completion if not specified."""
        if self.total_tokens == 0 and (self.prompt_tokens > 0 or self.completion_tokens > 0):
            self.total_tokens = self.prompt_tokens + self.completion_tokens
        return self


class CostEstimate(BaseModel):
    """Estimated financial cost in USD based on model pricing."""

    input_cost_usd: float = Field(default=0.0, ge=0.0)
    output_cost_usd: float = Field(default=0.0, ge=0.0)
    total_cost_usd: float = Field(default=0.0, ge=0.0)

    @model_validator(mode="after")
    def compute_total_cost(self) -> "CostEstimate":
        """Compute total cost if not explicitly assigned."""
        if self.total_cost_usd == 0.0 and (self.input_cost_usd > 0 or self.output_cost_usd > 0):
            self.total_cost_usd = round(self.input_cost_usd + self.output_cost_usd, 6)
        return self


class GatewayRequest(BaseModel):
    """Standardized request payload dispatched to the LLM Gateway."""

    messages: List[ChatMessage] = Field(
        default_factory=list,
        description="Structured message history",
    )
    prompt: Optional[str] = Field(
        default=None,
        description="Convenience single text prompt (converted to user message if provided)",
    )
    provider: Optional[str] = Field(
        default=None,
        description="Explicit provider override (e.g., 'gemini', 'mistral')",
    )
    model: Optional[str] = Field(
        default=None,
        description="Explicit model identifier override",
    )
    temperature: float = Field(
        default=0.7,
        ge=0.0,
        le=2.0,
        description="Sampling temperature",
    )
    max_tokens: Optional[int] = Field(
        default=1024,
        gt=0,
        description="Maximum tokens to generate",
    )
    top_p: Optional[float] = Field(
        default=0.95,
        ge=0.0,
        le=1.0,
        description="Nucleus sampling threshold",
    )
    stop_sequences: List[str] = Field(
        default_factory=list,
        description="Optional list of stop sequences",
    )
    request_id: Optional[str] = Field(
        default=None,
        description="Correlation ID for tracing this request",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Arbitrary caller metadata for tracing and logging",
    )

    @model_validator(mode="after")
    def validate_content(self) -> "GatewayRequest":
        """Ensure either prompt or messages is provided; convert prompt to message."""
        if not self.messages and not self.prompt:
            raise ValueError("Either 'prompt' or non-empty 'messages' must be provided.")
        if self.prompt and not self.messages:
            self.messages = [ChatMessage(role=Role.USER, content=self.prompt)]
        return self


class GatewayResponse(BaseModel):
    """Standardized response emitted by the LLM Gateway."""

    content: str = Field(..., description="Generated text completion")
    provider: str = Field(..., description="Provider that generated the completion")
    model: str = Field(..., description="Model identifier used")
    finish_reason: Optional[str] = Field(default="stop", description="Reason for generation completion")
    usage: TokenUsage = Field(default_factory=TokenUsage, description="Token consumption details")
    cost: CostEstimate = Field(default_factory=CostEstimate, description="Estimated USD cost")
    latency_ms: float = Field(default=0.0, ge=0.0, description="Latency of the call in milliseconds")
    request_id: Optional[str] = Field(default=None, description="Associated request correlation ID")
    attempts: int = Field(default=1, ge=1, description="Number of attempts made across providers")
    fallback_triggered: bool = Field(default=False, description="True if primary failed and fallback was used")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional provider metadata")
